// Defines file organization strategies and content generation logic

import { formatAsComment } from "./languageUtils.js";

/**
 * Generate the README markdown content
 * @param {Object} problemData 
 * @returns {string}
 */
export function buildReadmeContent(problemData) {
    try {
        const title = problemData.title || "";
        const url = problemData.url || "";
        const tags = (problemData.tags || []).join(", ");
        const difficulty = problemData.difficulty || "";

        // Strip basic HTML tags for cleaner markdown if needed, 
        // but keeping simple logic consistent with previous implementation
        let description = "";
        if (problemData.contentHtml) {
            // Basic strip:
            description = problemData.contentHtml.replace(/<[^>]+>/g, "").trim();
        }

        const lines = [];
        lines.push(`# ${title}`);
        lines.push("");
        if (difficulty) lines.push(`**Difficulty:** ${difficulty}`);
        if (tags) lines.push(`**Tags:** ${tags}`);
        if (url) lines.push(`**URL:** ${url}`);
        lines.push("");
        if (description) {
            lines.push("## Problem");
            lines.push("");
            lines.push(description);
            lines.push("");
        }
        lines.push("---");
        lines.push("_Generated by CodeBridge_"); // Unified footer
        return lines.join("\n");
    } catch (e) {
        return `# ${problemData.title || "Problem"}\n\n${problemData.url || ""}`;
    }
}

/**
 * Generate the list of files to upload based on the selected strategy
 * @param {string} strategy - 'folder' or 'flat'
 * @param {Object} problemData - data gathered from LeetCode
 * @param {string} chosenExt - file extension (e.g. 'py')
 * @returns {Array<{path: string, content: string}>}
 */
export function generateUploadFiles(strategy, problemData, chosenExt) {
    const folderName = problemData.folderName; // e.g. "0001-two-sum"
    const solutionContent = problemData.code || "";
    const readmeContent = buildReadmeContent(problemData);

    // Strategy: FOLDER (Default)
    // - Creates a folder per problem
    // - Separate README.md and solution file
    if (strategy !== 'flat') {
        return [
            {
                path: `${folderName}/solution.${chosenExt}`,
                content: solutionContent
            },
            {
                path: `${folderName}/README.md`,
                content: readmeContent
            }
        ];
    }

    // Strategy: FLAT
    // - No folder, just files in root (or parent folder if specified externally)
    // - PROBLEM DESCRIPTION IS EMBEDDED as a comment block at top of solution
    // - No separate README.md to keep it clean (as requested)

    // 1. Generate local readme text (without the header metadata potentially, or just use full?)
    // User requested: "use it to write the question with teh multi line comment start andn end defined"
    const descriptionComment = formatAsComment(readmeContent, chosenExt);

    // 2. Combine: Comment + Double Newline + Code
    const combinedContent = `${descriptionComment}\n\n${solutionContent}`;

    const filename = `${folderName}.${chosenExt}`;

    return [
        {
            path: filename,
            content: combinedContent
        }
    ];
}
